### ISSUE TITLE
excel表导出格式错误

### ISSUE THREAD

**Issue by teacherpan** [yunzhiclub/schedule#143]
![image](https://user-images.githubusercontent.com/12424383/220252112-4004a0b7-6dbd-4996-94e0-713e40dcab57.png)
1. 导出的EXCEL按大节显示
2. 某个大节中，有多个课程的，应该在一个单元格中换行

下图明显不对：
![image](https://user-images.githubusercontent.com/12424383/220252399-a706ca16-7936-49d1-b458-7fba3745900f.png)

**Comment by teacherpan** [comment]
此问题属于功能性问题，需要优先解决。

**Comment by HHepan** [comment]
<img width="1120" alt="f613c3015daaa39e8a029a1de5458c6b6a01e74c917ead267b9fb461468e36c0QzpcVXNlcnNcSEhISEhISEhQXEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1wyNTk3MjEzNjcyX3YyXEltYWdlRmlsZXNcMTY3Njk2NTUxODgwMF9DRkZFQUZGMi1FNkJCLTRkOGMtQjJFMS05MDVCQ0RBOEQ4RDUucG5n" src="https://user-images.githubusercontent.com/100888986/220280705-7132947c-f507-4079-adba-42eb0f6a5c13.png">

1.当前1,2栏就表示第一大节，3,4栏就第二大节，每个星期几下面都是5大节，是需要将“1,2(8:00 - 9:35)”改成“一(8:00 - 9:35)”这样吗？
2.侧边栏有周次显示，当同天同节同周时可以做到不同排课在同一个单元格中换行，如下图
<img width="1120" alt="02cdebec958a49a90cc75fa593820ee9df03701a05f7cecc912093414322180bQzpcVXNlcnNcSEhISEhISEhQXEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1wyNTk3MjEzNjcyX3YyXEltYWdlRmlsZXNcMTY3Njk2NTc0MjUwN181RDg0QzIzMS1BMjU5LTRmNzctOUYwRS1BRTdDMTZGOERDQUQucG5n" src="https://user-images.githubusercontent.com/100888986/220282021-6666ddcf-d79e-457b-8cd1-03fe818c8870.png">

**Comment by teacherpan** [comment]
![image](https://user-images.githubusercontent.com/12424383/220282865-fc5cb732-dc92-4000-a91e-5909c5b5c3a8.png)
问题出在这，左边栏应该是显示第几大节，和那个html一样。而不是第几周。
第几周的信息显示在单元格中。
可以在看一下原始的课表格式。
